#pragma once

#define PIN_HV_SENSE GPIO_NUM_2
#define PIN_HV_DRIVE GPIO_NUM_3

#define PIN_I2C_SCL GPIO_NUM_4
#define PIN_I2C_SDA GPIO_NUM_5

#define PIN_PULSE_IN GPIO_NUM_0

#define PIN_LED_R GPIO_NUM_6
#define PIN_LED_G GPIO_NUM_1
#define PIN_LED_B GPIO_NUM_7

#define PIN_BUZZER GPIO_NUM_18
#define PIN_USB_STATUS  GPIO_NUM_21

