name: esp-idf build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Prepare ccache timestamp
        id: ccache_cache_keys
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: ccache cache
        uses: actions/cache@v4
        with:
          path: /home/runner/.ccache
          key: esp-idf-ccache-${{ runner.os }}-${{ github.ref }}-${{ steps.ccache_cache_keys.outputs.date }}
          restore-keys: |
            esp-idf-ccache-${{ runner.os }}-${{ github.ref }}-
            esp-idf-ccache-${{ runner.os }}-

      - name: Build with ESP-IDF
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.1
          target: esp32c6
          command: |
            export IDF_CCACHE_ENABLE=1
            export CCACHE_DIR=/home/runner/.ccache
            idf.py build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            build/*.bin
            build/partition_table/*.bin
            build/bootloader/*.bin
            build/flasher_args.json